# Generated by Django 5.0.7 on 2024-07-15 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theaters', '0002_seating_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seating',
            name='theater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seatings', to='theaters.theater'),
        ),
    ]
